# sige infomation
site_name: BacklightBlog

# settings
theme:
  name: material
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
    primary: 'white'
    accent: 'red'
  language: 'zh'
  favicon: 'https://cdn.jsdelivr.net/npm/oicdn@0.0.1/favicon.ico'

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

# navigation
nav:
  - 主页:
    - 你好，世界: index.md
    - 简介: index/intro.md
    - 作者: index/author.md
  - 测试:
    - 代码高亮测试: test/code-test.md
    - 数学公式测试: test/math-test.md
    - 脚注测试: test/footnotes-test.md